project_id = "rezervujkurt"

[auth]
site_url = "https://<CODESPACE_NAME>-3000.app.github.dev"
additional_redirect_urls = [
  "https://<CODESPACE_NAME>-3000.app.github.dev",
  "https://<CODESPACE_NAME>-3000.app.github.dev/rezervace",
  "http://localhost:3000",
  "http://localhost:3000/rezervace"
]

[auth.email.template.magic_link]
subject = "Přihlášení do RezervujKurt"
content_path = "./supabase/templates/magic_link.html"
