-- Základní doménové schéma pro rezervační systém.
-- Cíl: bezpečný datový základ bez zásahu do UI.

create extension if not exists btree_gist;

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null,
  phone text,
  role text not null default 'user' check (role in ('user', 'member', 'admin')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.courts (
  id bigint generated by default as identity primary key,
  name text not null unique,
  surface text not null default 'antuka',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.reservations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles (id) on delete restrict,
  court_id bigint not null references public.courts (id) on delete restrict,
  reservation_date date not null,
  time_from time not null,
  time_to time not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'cancelled')),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (time_from < time_to)
);

-- Unikátnost přesného slotu (jak bylo požadováno v zadání).
create unique index if not exists reservations_exact_slot_uq
  on public.reservations (court_id, reservation_date, time_from, time_to);

-- Silnější ochrana proti překryvu rezervací na stejném kurtu v jednom dni.
alter table public.reservations
  add constraint reservations_no_overlap_excl
  exclude using gist (
    court_id with =,
    reservation_date with =,
    tsrange(
      (reservation_date::timestamp + time_from),
      (reservation_date::timestamp + time_to),
      '[)'
    ) with &&
  )
  where (status in ('pending', 'approved'));

create table if not exists public.reservation_audit_log (
  id bigint generated by default as identity primary key,
  reservation_id uuid not null references public.reservations (id) on delete cascade,
  changed_by uuid references public.profiles (id) on delete set null,
  action text not null,
  old_status text,
  new_status text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check (
    (old_status is null or old_status in ('pending', 'approved', 'cancelled'))
    and (new_status is null or new_status in ('pending', 'approved', 'cancelled'))
  )
);

create index if not exists reservations_user_idx on public.reservations (user_id);
create index if not exists reservations_court_date_idx on public.reservations (court_id, reservation_date);
create index if not exists reservation_audit_log_reservation_idx on public.reservation_audit_log (reservation_id);

alter table public.profiles enable row level security;
alter table public.courts enable row level security;
alter table public.reservations enable row level security;
alter table public.reservation_audit_log enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  );
$$;

-- profiles policies
create policy "profiles_select_self_or_admin"
  on public.profiles
  for select
  using (id = auth.uid() or public.is_admin());

create policy "profiles_update_self_or_admin"
  on public.profiles
  for update
  using (id = auth.uid() or public.is_admin())
  with check (id = auth.uid() or public.is_admin());

create policy "profiles_insert_self"
  on public.profiles
  for insert
  with check (id = auth.uid() or public.is_admin());

-- courts policies (read pro všechny přihlášené, write jen admin)
create policy "courts_select_authenticated"
  on public.courts
  for select
  using (auth.role() = 'authenticated');

create policy "courts_modify_admin"
  on public.courts
  for all
  using (public.is_admin())
  with check (public.is_admin());

-- reservations policies
create policy "reservations_select_owner_or_admin"
  on public.reservations
  for select
  using (user_id = auth.uid() or public.is_admin());

create policy "reservations_insert_owner_or_admin"
  on public.reservations
  for insert
  with check (user_id = auth.uid() or public.is_admin());

create policy "reservations_update_owner_or_admin"
  on public.reservations
  for update
  using (user_id = auth.uid() or public.is_admin())
  with check (user_id = auth.uid() or public.is_admin());

create policy "reservations_delete_admin"
  on public.reservations
  for delete
  using (public.is_admin());

-- audit log policies
create policy "reservation_audit_log_select_owner_or_admin"
  on public.reservation_audit_log
  for select
  using (
    public.is_admin()
    or exists (
      select 1
      from public.reservations r
      where r.id = reservation_id and r.user_id = auth.uid()
    )
  );

create policy "reservation_audit_log_insert_admin"
  on public.reservation_audit_log
  for insert
  with check (public.is_admin());
