-- Transakční outbox pro serverové notifikace o nových rezervacích.
-- Trigger pouze zařadí událost ve stejné transakci jako rezervaci; síťové volání
-- provádí samostatný worker až po potvrzení transakce.

alter table public.profiles
  add column if not exists admin_notifications_enabled boolean not null default true;

create table if not exists public.notification_outbox (
  id bigint generated by default as identity primary key,
  event_type text not null,
  reservation_id uuid not null references public.reservations (id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'sent', 'failed')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  next_attempt_at timestamptz not null default now(),
  processing_started_at timestamptz,
  lock_token uuid,
  processed_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (event_type, reservation_id)
);

create index if not exists notification_outbox_pending_idx
  on public.notification_outbox (next_attempt_at, created_at)
  where status = 'pending';

alter table public.notification_outbox enable row level security;

-- Explicitní REVOKE chrání tabulku i v prostředí s dříve rozšířenými default grants.
-- Záměrně nevytváříme žádnou klientskou RLS policy.
revoke all privileges on public.notification_outbox from public;
revoke all privileges on public.notification_outbox from anon;
revoke all privileges on public.notification_outbox from authenticated;

create or replace function public.enqueue_reservation_created_notification()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.status <> 'pending' then
    return new;
  end if;

  insert into public.notification_outbox (
    event_type,
    reservation_id,
    payload
  )
  values (
    'reservation.created',
    new.id,
    jsonb_build_object(
      'reservation_id', new.id,
      'created_at', new.created_at
    )
  )
  on conflict (event_type, reservation_id) do nothing;

  return new;
end;
$$;

drop trigger if exists trg_reservation_created_notification on public.reservations;

create trigger trg_reservation_created_notification
after insert on public.reservations
for each row
execute function public.enqueue_reservation_created_notification();

-- Atomický claim používá SKIP LOCKED, takže paralelní workery nemohou získat
-- stejnou událost. Událost po vypršení lease může bezpečně převzít další běh.
create or replace function public.claim_notification_outbox(
  p_worker_token uuid,
  p_batch_size integer default 10,
  p_lease_seconds integer default 300
)
returns setof public.notification_outbox
language plpgsql
security definer
set search_path = public, pg_temp
set row_security = off
as $$
begin
  if p_worker_token is null then
    raise exception 'Worker token nesmí být prázdný.';
  end if;

  return query
  with claimable as (
    select o.id
    from public.notification_outbox o
    where (
      (
        o.status = 'pending'
        and o.next_attempt_at <= now()
      )
      or (
        o.status = 'processing'
        and o.processing_started_at < now() - make_interval(secs => greatest(p_lease_seconds, 30))
      )
    )
    order by o.created_at
    for update skip locked
    limit least(greatest(p_batch_size, 1), 50)
  )
  update public.notification_outbox o
  set
    status = 'processing',
    attempt_count = o.attempt_count + 1,
    processing_started_at = now(),
    lock_token = p_worker_token,
    updated_at = now()
  from claimable
  where o.id = claimable.id
  returning o.*;
end;
$$;

create or replace function public.complete_notification_outbox(
  p_event_id bigint,
  p_worker_token uuid
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
set row_security = off
as $$
declare
  v_updated_count integer;
begin
  update public.notification_outbox
  set
    status = 'sent',
    processed_at = now(),
    processing_started_at = null,
    lock_token = null,
    last_error = null,
    updated_at = now()
  where id = p_event_id
    and status = 'processing'
    and lock_token = p_worker_token;

  get diagnostics v_updated_count = row_count;
  return v_updated_count = 1;
end;
$$;

create or replace function public.fail_notification_outbox(
  p_event_id bigint,
  p_worker_token uuid,
  p_last_error text,
  p_retry_at timestamptz,
  p_terminal boolean default false
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
set row_security = off
as $$
declare
  v_updated_count integer;
begin
  update public.notification_outbox
  set
    status = case when p_terminal then 'failed' else 'pending' end,
    next_attempt_at = case when p_terminal then now() else p_retry_at end,
    processing_started_at = null,
    lock_token = null,
    processed_at = null,
    last_error = left(coalesce(nullif(btrim(p_last_error), ''), 'Neznámá chyba při odesílání.'), 500),
    updated_at = now()
  where id = p_event_id
    and status = 'processing'
    and lock_token = p_worker_token;

  get diagnostics v_updated_count = row_count;
  return v_updated_count = 1;
end;
$$;

revoke all on function public.claim_notification_outbox(uuid, integer, integer) from public;
revoke all on function public.claim_notification_outbox(uuid, integer, integer) from anon;
revoke all on function public.claim_notification_outbox(uuid, integer, integer) from authenticated;
revoke all on function public.complete_notification_outbox(bigint, uuid) from public;
revoke all on function public.complete_notification_outbox(bigint, uuid) from anon;
revoke all on function public.complete_notification_outbox(bigint, uuid) from authenticated;
revoke all on function public.fail_notification_outbox(bigint, uuid, text, timestamptz, boolean) from public;
revoke all on function public.fail_notification_outbox(bigint, uuid, text, timestamptz, boolean) from anon;
revoke all on function public.fail_notification_outbox(bigint, uuid, text, timestamptz, boolean) from authenticated;

grant execute on function public.claim_notification_outbox(uuid, integer, integer) to service_role;
grant execute on function public.complete_notification_outbox(bigint, uuid) to service_role;
grant execute on function public.fail_notification_outbox(bigint, uuid, text, timestamptz, boolean) to service_role;
