-- Izolovaný datový základ pro budoucí GoPay platby.
-- Migrace je záměrně aditivní: nemění rezervace, statusy rezervací ani současné aplikační flow.

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  reservation_id uuid not null references public.reservations (id) on delete restrict,
  provider text not null default 'gopay',
  provider_payment_id text,
  idempotency_key text not null,
  amount_cents integer not null,
  currency text not null default 'CZK',
  status text not null default 'created',
  expires_at timestamptz,
  paid_at timestamptz,
  failed_at timestamptz,
  cancelled_at timestamptz,
  refunded_amount_cents integer not null default 0,
  refund_status text not null default 'not_requested',
  provider_refund_id text,
  refund_requested_at timestamptz,
  refunded_at timestamptz,
  last_error text,
  attempt_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payments_provider_chk check (provider in ('gopay')),
  constraint payments_amount_cents_chk check (amount_cents > 0),
  constraint payments_currency_chk check (currency = 'CZK'),
  constraint payments_status_chk check (
    status in (
      'created',
      'awaiting_payment',
      'paid',
      'failed',
      'cancelled',
      'expired',
      'requires_manual_review'
    )
  ),
  constraint payments_refund_status_chk check (
    refund_status in (
      'not_requested',
      'not_eligible',
      'requested',
      'processing',
      'succeeded',
      'failed',
      'manual_review'
    )
  ),
  constraint payments_refunded_amount_cents_chk check (
    refunded_amount_cents >= 0
    and refunded_amount_cents <= amount_cents
  ),
  constraint payments_attempt_count_chk check (attempt_count >= 0),
  constraint payments_last_error_length_chk check (last_error is null or char_length(last_error) <= 1000),
  constraint payments_metadata_object_chk check (jsonb_typeof(metadata) = 'object'),
  constraint payments_id_reservation_uq unique (id, reservation_id)
);

create unique index if not exists payments_idempotency_key_uq
  on public.payments (idempotency_key);

create unique index if not exists payments_provider_payment_id_uq
  on public.payments (provider, provider_payment_id)
  where provider_payment_id is not null;

create unique index if not exists payments_one_active_per_reservation_uq
  on public.payments (reservation_id)
  where status in ('created', 'awaiting_payment', 'paid', 'requires_manual_review');

create index if not exists payments_reservation_idx
  on public.payments (reservation_id);

create index if not exists payments_active_expires_at_idx
  on public.payments (expires_at)
  where status in ('created', 'awaiting_payment') and expires_at is not null;

create index if not exists payments_refund_attention_idx
  on public.payments (refund_status, updated_at)
  where refund_status in ('requested', 'processing', 'failed', 'manual_review');

create table if not exists public.payment_audit_log (
  id bigint generated by default as identity primary key,
  payment_id uuid not null,
  reservation_id uuid not null,
  event_type text not null,
  old_status text,
  new_status text,
  old_refund_status text,
  new_refund_status text,
  reason text,
  source text not null,
  attempt_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint payment_audit_log_payment_reservation_fk
    foreign key (payment_id, reservation_id)
    references public.payments (id, reservation_id)
    on delete cascade,
  constraint payment_audit_log_event_type_chk check (
    event_type in (
      'payment_created',
      'provider_payment_created',
      'payment_verification_started',
      'payment_verified',
      'payment_verification_failed',
      'payment_expired',
      'refund_requested',
      'refund_processing',
      'refund_succeeded',
      'refund_failed',
      'manual_review_required',
      'reconciliation_started',
      'reconciliation_completed'
    )
  ),
  constraint payment_audit_log_payment_statuses_chk check (
    (old_status is null or old_status in ('created', 'awaiting_payment', 'paid', 'failed', 'cancelled', 'expired', 'requires_manual_review'))
    and (new_status is null or new_status in ('created', 'awaiting_payment', 'paid', 'failed', 'cancelled', 'expired', 'requires_manual_review'))
  ),
  constraint payment_audit_log_refund_statuses_chk check (
    (old_refund_status is null or old_refund_status in ('not_requested', 'not_eligible', 'requested', 'processing', 'succeeded', 'failed', 'manual_review'))
    and (new_refund_status is null or new_refund_status in ('not_requested', 'not_eligible', 'requested', 'processing', 'succeeded', 'failed', 'manual_review'))
  ),
  constraint payment_audit_log_attempt_count_chk check (attempt_count >= 0),
  constraint payment_audit_log_reason_length_chk check (reason is null or char_length(reason) <= 1000),
  constraint payment_audit_log_source_chk check (source in ('app_server', 'gopay_webhook', 'reconciliation', 'admin_tool', 'db_migration')),
  constraint payment_audit_log_metadata_object_chk check (jsonb_typeof(metadata) = 'object')
);

create index if not exists payment_audit_log_payment_idx
  on public.payment_audit_log (payment_id, created_at desc);

create index if not exists payment_audit_log_reservation_idx
  on public.payment_audit_log (reservation_id, created_at desc);

alter table public.payments enable row level security;
alter table public.payment_audit_log enable row level security;

revoke all privileges on public.payments from anon, authenticated;
revoke all privileges on public.payment_audit_log from anon, authenticated;
