-- Serverově spravované provozní kill switche pro budoucí platební flow.
-- Migrace je aditivní a současný rezervační systém ji nepoužívá.

create table public.payment_feature_flags (
  flag_name text primary key,
  enabled boolean not null default false,
  description text not null,
  owner text not null,
  removal_condition text not null,
  updated_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payment_feature_flags_name_chk check (
    flag_name in (
      'gopay_create_enabled',
      'gopay_webhook_processing_enabled',
      'payment_expiration_enabled',
      'auto_refund_enabled',
      'payment_admin_monitoring_enabled'
    )
  ),
  constraint payment_feature_flags_description_length_chk check (char_length(description) between 1 and 500),
  constraint payment_feature_flags_owner_length_chk check (char_length(owner) between 1 and 120),
  constraint payment_feature_flags_removal_condition_length_chk check (char_length(removal_condition) between 1 and 1000)
);


create table public.payment_feature_flag_audit_log (
  id bigint generated by default as identity primary key,
  flag_name text not null,
  old_enabled boolean,
  new_enabled boolean not null,
  changed_by uuid,
  reason text,
  source text not null,
  created_at timestamptz not null default now(),
  constraint payment_feature_flag_audit_log_flag_name_chk check (
    flag_name in (
      'gopay_create_enabled',
      'gopay_webhook_processing_enabled',
      'payment_expiration_enabled',
      'auto_refund_enabled',
      'payment_admin_monitoring_enabled'
    )
  ),
  constraint payment_feature_flag_audit_log_reason_length_chk check (reason is null or char_length(reason) <= 1000),
  constraint payment_feature_flag_audit_log_source_chk check (source in ('db_migration', 'admin_tool', 'app_server', 'incident_response'))
);


alter table public.payment_feature_flags enable row level security;
alter table public.payment_feature_flag_audit_log enable row level security;

revoke all privileges on public.payment_feature_flags from anon, authenticated;
revoke all privileges on public.payment_feature_flag_audit_log from anon, authenticated;
revoke all privileges on sequence public.payment_feature_flag_audit_log_id_seq from anon, authenticated;

-- Budoucí serverové routy musí umět bezpečně číst kill switche přes service role.
grant select on table public.payment_feature_flags to service_role;

insert into public.payment_feature_flags (flag_name, enabled, description, owner, removal_condition)
values
  (
    'gopay_create_enabled',
    false,
    'Povoluje vytvoření nové GoPay platby pro nečlenskou rezervaci.',
    'vlastnik-projektu',
    'Po stabilním spuštění plateb vyhodnotit, zda zůstane jako trvalý incident kill switch.'
  ),
  (
    'gopay_webhook_processing_enabled',
    false,
    'Povoluje zpracování GoPay webhooků pro již existující platby.',
    'vlastnik-projektu',
    'Ponechat jako provozní kill switch, pokud webhook bude produkčně aktivní.'
  ),
  (
    'payment_expiration_enabled',
    false,
    'Povoluje automatickou expiraci nezaplacených platebních rezervací.',
    'vlastnik-projektu',
    'Ponechat jako provozní kill switch pro expirační worker, pokud bude produkčně aktivní.'
  ),
  (
    'auto_refund_enabled',
    false,
    'Povoluje automatické zahájení refundu plateb.',
    'vlastnik-projektu',
    'Po ověření refund procesu rozhodnout, zda automatika zůstane zapínaná samostatně.'
  ),
  (
    'payment_admin_monitoring_enabled',
    false,
    'Povoluje budoucí administrátorský provozní přehled plateb.',
    'vlastnik-projektu',
    'Po dodání bezpečného admin monitoringu rozhodnout, zda flag odstranit.'
  );

insert into public.payment_feature_flag_audit_log (flag_name, old_enabled, new_enabled, source, reason)
select
  flag_name,
  null,
  enabled,
  'db_migration',
  'Inicializace bezpečně vypnutých platebních provozních flagů.'
from public.payment_feature_flags;
